---

- name: Clonar o repositorio do projeto OpenStack DEV
  git:
    repo: https://opendev.org/openstack/devstack.git
    version: master
    dest: /devstack/
  become: yes

- name: Enviar o arquivo de configuração local.conf
  copy:
    src: '../conf/local.conf'
    dest: '/devstack/local.conf'
  become: yes

- name: Criar usuario e grupo stack, por meio do script padrão.
  shell: /devstack/tools/create-stack-user.sh
  become: yes
  
- name: Altera a permissão do diretorio devstack
  file:
    path: /devstack/
    owner: stack
    group: stack
    state: directory
    recurse: yes
  become: yes

- name: Executa o script stack.sh.
  shell: /devstack/stack.sh
  become: yes
  become_user: stack